#!/usr/bin/env python
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
fitness_init.py — emit CI fitness functions that LOCK clean-architecture boundaries.

A clean-refactorer run separates code into domain / application / infrastructure / interfaces with
the Dependency Rule (inner layers depend on nothing outward). That structure rots the moment it
isn't enforced. This script emits a fitness function the TARGET repo's CI runs on every PR, FAILING
the build when someone re-introduces a forbidden cross-layer import, a cycle, or an orphan:

  JS/TS   -> `.dependency-cruiser.js`   (forbidden cross-layer + circular + orphan rules)
             wire `depcruise --validate src` into CI.
  Java    -> an ArchUnit JUnit test     (layered-architecture + package access + no-cycles)
             runs as a normal test.
  Python  -> an import-linter `.importlinter` layered contract (bonus; FastAPI fleet).

READ-ONLY on existing source: it only CREATES config/test files, never overwrites without --force,
and writes only into the target repo. Missing tools are reported (skip-on-missing ethos), not fatal.
It scaffolds config; it does NOT run the target's build.

Usage:
  uv run fitness_init.py <repo> [--src src] [--base-package com.example] [--force] [--dry-run]
"""
from __future__ import annotations
import argparse, json, shutil, subprocess, sys
from pathlib import Path

TOOL = "fitness_init"
LAYERS = ["domain", "application", "infrastructure", "interfaces"]


def log(msg: str) -> None:
    print(f"[{TOOL}] {msg}", file=sys.stderr)


def have(tool: str) -> bool:
    return shutil.which(tool) is not None


def run(cmd: list[str], cwd: Path) -> tuple[int, str, str]:
    log("$ " + " ".join(cmd))
    try:
        p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=300)
        return p.returncode, p.stdout, p.stderr
    except FileNotFoundError:
        return 127, "", f"not found: {cmd[0]}"
    except subprocess.TimeoutExpired:
        return 124, "", "timeout"


def detect_stack(repo: Path) -> set[str]:
    s: set[str] = set()
    names = {p.name for p in repo.rglob("*") if p.is_file() and ".git" not in p.parts}
    if "pom.xml" in names or any(repo.rglob("build.gradle*")):
        s.add("java")
    if "package.json" in names:
        s.add("node")
        try:
            pkg = json.loads(next(repo.rglob("package.json")).read_text("utf-8"))
            dep = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
            if "typescript" in dep:
                s.add("ts")
        except Exception:
            pass
    if "pyproject.toml" in names or "requirements.txt" in names or any(repo.rglob("*.py")):
        s.add("python")
    return s


def write(path: Path, content: str, force: bool, dry: bool) -> bool:
    if path.exists() and not force:
        log(f"SKIP (exists, use --force): {path}")
        return False
    if dry:
        log(f"DRY would write: {path}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    log(f"wrote: {path}")
    return True


# --------------------------------------------------------------------------- JS / TS
def depcruiser_config(src: str) -> str:
    return f'''\
/**
 * dependency-cruiser fitness function — generated by clean-refactorer/fitness_init.py.
 *
 * Enforces clean-architecture boundaries so they cannot silently rot. The Dependency Rule:
 * inner layers must not import outer ones.
 *   domain         -> imports nothing in {src}/ outward (pure)
 *   application     -> may import domain
 *   infrastructure  -> may import domain, application
 *   interfaces      -> may import application, domain (NOT infrastructure directly)
 *
 * CI:  npx depcruise --config .dependency-cruiser.js --validate {src}
 *      (exit != 0 on any 'error'-severity violation -> build fails)
 *
 * Install:  npm i -D dependency-cruiser
 */
module.exports = {{
  forbidden: [
    {{
      name: "no-circular",
      comment: "Cycles couple layers and block incremental refactor/revert.",
      severity: "error",
      from: {{}},
      to: {{ circular: true }},
    }},
    {{
      name: "no-orphans",
      comment: "Orphan modules are usually dead code left by a half-finished move.",
      severity: "warn",
      from: {{ orphan: true, pathNot: ["\\\\.(d\\\\.ts|test|spec)\\\\.[jt]sx?$", "(^|/)__"] }},
      to: {{}},
    }},
    {{
      name: "domain-is-pure",
      comment: "domain/ must depend on NOTHING outward (no app/infra/interfaces, no framework).",
      severity: "error",
      from: {{ path: "^{src}/domain" }},
      to: {{ path: "^{src}/(application|infrastructure|interfaces)" }},
    }},
    {{
      name: "domain-no-framework",
      comment: "domain/ stays framework-free (no React/axios/orm).",
      severity: "error",
      from: {{ path: "^{src}/domain" }},
      to: {{ path: "node_modules/(react|react-dom|axios|@?prisma|typeorm|express|@nestjs)" }},
    }},
    {{
      name: "application-only-domain",
      comment: "application/ orchestrates domain via ports; no infra/interfaces, no framework.",
      severity: "error",
      from: {{ path: "^{src}/application" }},
      to: {{ path: "^{src}/(infrastructure|interfaces)" }},
    }},
    {{
      name: "interfaces-not-infrastructure",
      comment: "Controllers/UI talk to use cases, not directly to DB/HTTP adapters.",
      severity: "error",
      from: {{ path: "^{src}/interfaces" }},
      to: {{ path: "^{src}/infrastructure" }},
    }},
  ],
  options: {{
    doNotFollow: {{ path: "node_modules" }},
    tsConfig: {{ fileName: "tsconfig.json" }},
    tsPreCompilationDeps: true,
    enhancedResolveOptions: {{ exportsFields: ["exports"], conditionNames: ["import", "require"] }},
  }},
}};
'''


# --------------------------------------------------------------------------- Java
def archunit_test(base_pkg: str) -> str:
    return f'''\
package architecture;

import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;

import static com.tngtech.archunit.library.Architectures.layeredArchitecture;
import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;

/**
 * ArchUnit fitness function — generated by clean-refactorer/fitness_init.py.
 *
 * Enforces clean-architecture boundaries as a normal JUnit test (fails the build on violation).
 * The Dependency Rule: inner layers must not depend on outer ones.
 *
 * Maven (test scope):  com.tngtech.archunit:archunit-junit5
 * Run:                 mvn test   (or your CI's test phase)
 *
 * Adjust the base package below to YOUR root package.
 */
@AnalyzeClasses(packages = "{base_pkg}", importOptions = ImportOption.DoNotIncludeTests.class)
class LayeredArchitectureTest {{

    @ArchTest
    static final ArchRule layered = layeredArchitecture().consideringAllDependencies()
        .layer("Domain").definedBy("{base_pkg}.domain..")
        .layer("Application").definedBy("{base_pkg}.application..")
        .layer("Infrastructure").definedBy("{base_pkg}.infrastructure..")
        .layer("Interfaces").definedBy("{base_pkg}.interfaces..")
        // Who may be depended on BY whom:
        .whereLayer("Interfaces").mayNotBeAccessedByAnyLayer()
        .whereLayer("Infrastructure").mayOnlyBeAccessedByLayers("Interfaces")
        .whereLayer("Application").mayOnlyBeAccessedByLayers("Interfaces", "Infrastructure")
        .whereLayer("Domain").mayOnlyBeAccessedByLayers("Application", "Infrastructure", "Interfaces");

    @ArchTest
    static final ArchRule domainIsPure = com.tngtech.archunit.lang.syntax.ArchRuleDefinition
        .noClasses().that().resideInAPackage("{base_pkg}.domain..")
        .should().dependOnClassesThat().resideInAnyPackage(
            "{base_pkg}.infrastructure..", "{base_pkg}.interfaces..",
            "org.springframework..", "jakarta.persistence..", "javax.persistence..")
        .as("domain must depend on nothing outward and stay framework-free");

    @ArchTest
    static final ArchRule noCycles = slices()
        .matching("{base_pkg}.(*)..")
        .should().beFreeOfCycles();
}}
'''


# --------------------------------------------------------------------------- Python (bonus)
def importlinter_config(pkg: str) -> str:
    return f'''\
# import-linter fitness function — generated by clean-refactorer/fitness_init.py.
# Enforces the clean-architecture layering for the FastAPI/Python fleet.
#   install:  pip install import-linter
#   run (CI): lint-imports
# Inner layers must not import outer ones (top of the list = highest-level / outermost).
[importlinter]
root_package = {pkg}

[importlinter:contract:layers]
name = Clean architecture layers
type = layers
layers =
    {pkg}.interfaces
    {pkg}.infrastructure
    {pkg}.application
    {pkg}.domain

[importlinter:contract:domain-pure]
name = Domain depends on nothing outward and no framework
type = forbidden
source_modules =
    {pkg}.domain
forbidden_modules =
    {pkg}.application
    {pkg}.infrastructure
    {pkg}.interfaces
    fastapi
    sqlalchemy
    pydantic
'''


CI_HINT = """\
# Wire the fitness function into CI (example, GitHub Actions step):
#
#   JS/TS:
#     - run: npm i -D dependency-cruiser
#     - run: npx depcruise --config .dependency-cruiser.js --validate %SRC%
#
#   Java (Maven): the ArchUnit test runs in the normal `mvn test` phase — no extra step.
#
#   Python:
#     - run: pip install import-linter && lint-imports
#
# A violation -> non-zero exit -> the build fails. That is the lock.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="Emit CI fitness functions locking clean-arch boundaries.")
    ap.add_argument("repo")
    ap.add_argument("--src", default="src", help="JS/TS source root (default: src)")
    ap.add_argument("--base-package", default="com.example",
                    help="Java root package for the ArchUnit rules (default: com.example)")
    ap.add_argument("--py-package", default=None,
                    help="Python root package for import-linter (default: auto/first dir)")
    ap.add_argument("--force", action="store_true", help="overwrite existing config files")
    ap.add_argument("--dry-run", action="store_true", help="show what would be written, write nothing")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()
    if not repo.exists():
        log(f"no such repo: {repo}")
        return 2

    stacks = detect_stack(repo)
    log(f"detected stacks: {sorted(stacks) or ['?']}")
    emitted: list[str] = []

    if "node" in stacks:
        if write(repo / ".dependency-cruiser.js", depcruiser_config(args.src), args.force, args.dry_run):
            emitted.append(".dependency-cruiser.js (depcruise --validate)")
        if not have("npx"):
            log("note: `npx` not on PATH — `npm i -D dependency-cruiser`, then `npx depcruise --validate`.")

    if "java" in stacks:
        test_dir = repo / "src" / "test" / "java" / "architecture"
        if write(test_dir / "LayeredArchitectureTest.java",
                 archunit_test(args.base_package), args.force, args.dry_run):
            emitted.append(f"ArchUnit LayeredArchitectureTest.java (base pkg: {args.base_package})")

    if "python" in stacks:
        pkg = args.py_package
        if not pkg:
            # best-effort: first top-level package dir with an __init__.py
            for d in sorted(repo.iterdir()):
                if d.is_dir() and (d / "__init__.py").exists():
                    pkg = d.name
                    break
            pkg = pkg or "app"
        if write(repo / ".importlinter", importlinter_config(pkg), args.force, args.dry_run):
            emitted.append(f".importlinter (root package: {pkg})")
        if not have("lint-imports"):
            log("note: import-linter not installed — `pip install import-linter`, then `lint-imports`.")

    if not emitted:
        log("no supported stack detected (JS/TS, Java, or Python). Nothing emitted.")
        return 1

    write(repo / "FITNESS_CI.txt", CI_HINT.replace("%SRC%", args.src), args.force, args.dry_run)

    print(json.dumps({
        "stacks": sorted(stacks),
        "emitted": emitted,
        "next": "Commit these, then WIRE them into CI (see FITNESS_CI.txt) so a forbidden "
                "cross-layer import / cycle / orphan FAILS the build.",
    }, indent=2))
    log("Fitness functions emitted. Boundaries are locked once these run in CI.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
