#!/usr/bin/env python
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
translate.py — the i18n agent's translation engine ("skill").

Generates the ~190 non-base locale files for a project from its AI-authored
base languages (en + pt-BR) using Google's free, keyless `gtx` translate
endpoint (the same one decoded from InterPRO's TranslationService.java).

Design goals (per the agent's "systematic > agentic, save tokens" rule):
  * ZERO LLM tokens for the bulk languages — pure script.
  * Idempotent / incremental: only translates MISSING keys by default, so a
    re-run after a few new keys is cheap. A persistent cache makes re-runs free.
  * Framework-native: auto-detects `.properties` (Java/React) vs `.json`
    (i18next) from the base file, and emits the same format.
  * Safe: masks placeholders ({{var}}, {var}, %s, %1$s, <tags>, \n) before
    sending and restores them after; if a mask is lost in translation the
    original source string is kept rather than corrupting interpolation.
  * Never overwrites the base languages (en / pt-BR) — those are AI-authored.

Usage:
  uv run agents/i18n/translate.py --src <locales_dir> [opts]

Examples:
  # Fill all 190 langs for a Java/React .properties project (incremental):
  uv run agents/i18n/translate.py --src theAPIAniaAPP/frontend/public/locales

  # i18next JSON project, only generate 5 langs, dry-run:
  uv run agents/i18n/translate.py --src hey-ania/src/i18n --format json \
        --langs es,fr-FR,de,ja,ar --dry-run

  # Force re-translate everything (ignore existing target values + cache):
  uv run agents/i18n/translate.py --src <dir> --all --no-cache
"""
import argparse, json, os, re, sys, time, urllib.parse, urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

HERE = os.path.dirname(os.path.abspath(__file__))
GTX = "https://translate.googleapis.com/translate_a/single"

# gtx target-code aliases for the few registry codes gtx spells differently.
GTX_ALIAS = {
    "pt-BR": "pt", "pt-PT": "pt-PT", "zh-CN": "zh-CN", "zh-TW": "zh-TW",
    "mni-Mtei": "mni-Mtei", "ms-Arab": "ms-Arab", "pa-Arab": "pa-Arab",
}

# Placeholders that MUST survive translation verbatim. Order matters (greedy first).
PLACEHOLDER_RE = re.compile(
    r"\{\{[^}]+\}\}"        # i18next {{var}}
    r"|\{[^{}]*\}"          # ICU / {var} / {0}
    r"|%(?:\d+\$)?[-+ 0#]*\d*(?:\.\d+)?[sdfxXeEgG@]"  # printf %s %d %1$s %.2f %+.3f %05d %@
    r"|<[^>]+>"             # html / xml tags
    r"|\\n|\\t|\\r"         # escaped whitespace
)


# ---------- format helpers ----------------------------------------------------
def detect_format(src, override):
    if override and override != "auto":
        return override
    for f in sorted(os.listdir(src)):
        if f.startswith("."):            # skip .translate-cache.json etc.
            continue
        if f.endswith(".properties"):
            return "properties"
        if f.endswith(".json"):
            return "json"
    return "properties"


def base_filename(code, fmt):
    return (f"{code}.json" if fmt == "json"
            else f"messages_{code}.properties")


def find_base_file(src, code, fmt):
    """Locate a base locale file allowing common naming variants."""
    cands = ([f"{code}.json"] if fmt == "json"
             else [f"messages_{code}.properties", f"{code}.properties"])
    for c in cands:
        p = os.path.join(src, c)
        if os.path.exists(p):
            return p
    return None


def load_properties(path):
    d = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            s = line.rstrip("\n")
            if not s.strip() or s.lstrip().startswith(("#", "!")):
                continue
            if "=" not in s:
                continue
            k, v = s.split("=", 1)
            d[k.strip()] = v
    return d


def dump_properties(path, items):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by agents/i18n/translate.py — do not hand-edit.\n")
        fh.write("# Base languages (en, pt-BR) are AI-authored; this file is machine-translated.\n")
        for k, v in items:
            fh.write(f"{k}={v}\n")


def flatten_json(obj, prefix=""):
    out = {}
    for k, v in obj.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            out.update(flatten_json(v, key))
        else:
            out[key] = v
    return out


def unflatten_json(flat):
    root = {}
    for k, v in flat.items():
        parts = k.split(".")
        node = root
        for p in parts[:-1]:
            node = node.setdefault(p, {})
        node[parts[-1]] = v
    return root


def load_json(path):
    with open(path, encoding="utf-8") as fh:
        return flatten_json(json.load(fh))


def dump_json(path, items):
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(unflatten_json(dict(items)), fh, ensure_ascii=False, indent=2)
        fh.write("\n")


# ---------- translation -------------------------------------------------------
def mask(text):
    holes = []

    def repl(m):
        holes.append(m.group(0))
        return f" ⟦{len(holes) - 1}⟧ "  # ⟦n⟧ — math brackets gtx leaves alone

    return PLACEHOLDER_RE.sub(repl, text), holes


def unmask(text, holes):
    for i, h in enumerate(holes):
        # gtx may drop the surrounding spaces or alter casing of the bracket pair
        for pat in (f"⟦{i}⟧", f"⟦ {i} ⟧", f"⟦{i} ⟧", f"⟦ {i}⟧"):
            text = text.replace(pat, h)
    return text


def gtx_translate(text, sl, tl, timeout, retries):
    masked, holes = mask(text)
    q = urllib.parse.quote(masked)
    url = f"{GTX}?client=gtx&sl={sl}&tl={tl}&dt=t&q={q}"
    req = urllib.request.Request(url, headers={
        "User-Agent": "Mozilla/5.0", "Accept": "application/json"})
    last = None
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                data = json.loads(r.read().decode("utf-8"))
            out = "".join(seg[0] for seg in data[0] if seg and seg[0])
            out = unmask(out, holes)
            # Safety: every placeholder must have survived, else keep source.
            if all(h in out for h in holes):
                return out
            return text
        except Exception as e:                       # noqa: BLE001
            last = e
            time.sleep(min(8, 0.5 * (2 ** attempt)))  # exp backoff
    raise RuntimeError(f"gtx failed sl={sl} tl={tl}: {last}")


# Batched variant: send many short strings in ONE gtx request, newline-joined.
# gtx keeps the line breaks as their own segments, so concatenating data[0] and
# splitting on the separator recovers a 1:1 aligned list. This collapses ~3000
# requests/lang into ~60, the difference between minutes and hours for ~190 langs.
# Returns None (caller falls back to per-key) if the split doesn't align, so a
# bad batch never corrupts output. Only single-line texts are batchable.
SEP = "\n"


def gtx_translate_batch(texts, sl, tl, timeout, retries):
    masks = [mask(t) for t in texts]
    joined = SEP.join(m for m, _ in masks)
    q = urllib.parse.quote(joined)
    url = f"{GTX}?client=gtx&sl={sl}&tl={tl}&dt=t&q={q}"
    req = urllib.request.Request(url, headers={
        "User-Agent": "Mozilla/5.0", "Accept": "application/json"})
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                data = json.loads(r.read().decode("utf-8"))
            out = "".join(seg[0] for seg in data[0] if seg and seg[0])
            parts = out.split(SEP)
            if len(parts) != len(texts):
                return None  # misaligned → caller falls back to per-key
            res = []
            for part, (_, holes), orig in zip(parts, masks, texts):
                u = unmask(part, holes)
                res.append(u if all(h in u for h in holes) else orig)
            return res
        except Exception:                            # noqa: BLE001
            time.sleep(min(8, 0.5 * (2 ** attempt)))
    return None


# ---------- main --------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description="Generate non-base locale files via free Google gtx.")
    ap.add_argument("--src", required=True, help="locales directory")
    ap.add_argument("--base", default="en,pt-BR", help="AI-authored base codes (comma sep, first = preferred source)")
    ap.add_argument("--format", default="auto", choices=["auto", "properties", "json"])
    ap.add_argument("--langs", default="all", help="'all' or comma-sep subset of target codes")
    ap.add_argument("--registry", default=os.path.join(HERE, "langs.json"))
    ap.add_argument("--all", action="store_true", help="re-translate even existing target keys")
    ap.add_argument("--no-cache", action="store_true")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--batch", type=int, default=48, help="keys per gtx request (1 = legacy per-key)")
    ap.add_argument("--timeout", type=int, default=15)
    ap.add_argument("--retries", type=int, default=4)
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    src = os.path.abspath(a.src)
    fmt = detect_format(src, a.format)
    bases = [b.strip() for b in a.base.split(",") if b.strip()]
    reg = json.load(open(a.registry, encoding="utf-8"))
    all_codes = [l["code"] for l in reg["languages"]]

    # Load base translations (preferred source first).
    base_data, source_code = {}, None
    for b in bases:
        bf = find_base_file(src, b, fmt)
        if bf:
            base_data[b] = load_json(bf) if fmt == "json" else load_properties(bf)
            if source_code is None:
                source_code = b
    if not base_data:
        sys.exit(f"ERROR: no base file ({bases}) found in {src} (format={fmt}).")

    # Merged source key set: prefer first base, fall back to others per key.
    src_strings, key_order = {}, []
    for b in bases:
        for k, v in base_data.get(b, {}).items():
            if k not in src_strings:
                src_strings[k] = (v, GTX_ALIAS.get(b, b))
                key_order.append(k)

    targets = (all_codes if a.langs == "all"
               else [c.strip() for c in a.langs.split(",")])
    targets = [c for c in targets if c not in bases]

    # cache: { "tl|sl|sourceText": "translation" }
    cache_path = os.path.join(src, ".translate-cache.json")
    cache = {}
    if not a.no_cache and os.path.exists(cache_path):
        try:
            cache = json.load(open(cache_path, encoding="utf-8"))
        except Exception:                            # noqa: BLE001
            cache = {}

    print(f"format={fmt} source={source_code} keys={len(key_order)} "
          f"targets={len(targets)} mode={'FULL' if a.all else 'only-missing'}"
          f"{' DRY-RUN' if a.dry_run else ''}")

    total_calls = 0
    for ci, code in enumerate(targets, 1):
        tl = GTX_ALIAS.get(code, code)
        out_path = os.path.join(src, base_filename(code, fmt))
        existing = {}
        if os.path.exists(out_path) and not a.all:
            existing = load_json(out_path) if fmt == "json" else load_properties(out_path)

        todo = [k for k in key_order if a.all or not existing.get(k)]
        if not todo:
            print(f"[{ci}/{len(targets)}] {code:<9} up-to-date")
            continue
        if a.dry_run:
            print(f"[{ci}/{len(targets)}] {code:<9} would translate {len(todo)} keys")
            continue

        results = dict(existing)
        n_err = 0

        # Resolve cached + empty keys up front; only the rest hit the network.
        pending = []  # (k, text, sl)
        for k in todo:
            text, sl = src_strings[k]
            if not text.strip():
                results[k] = text
                continue
            ck = f"{tl}|{sl}|{text}"
            if ck in cache:
                results[k] = cache[ck]
            else:
                pending.append((k, text, sl))

        # Batch by source lang; single-line texts go in batches, multiline per-key.
        batches = []  # list of list[(k,text,sl)]
        by_sl = {}
        for item in pending:
            (by_sl.setdefault(item[2], [])).append(item)
        for sl, items in by_sl.items():
            single = [it for it in items if SEP not in it[1]]
            multi = [it for it in items if SEP in it[1]]
            bs = max(1, a.batch)
            for i in range(0, len(single), bs):
                batches.append(single[i:i + bs])
            for it in multi:
                batches.append([it])

        def run_batch(batch):
            sl = batch[0][2]
            texts = [t for _, t, _ in batch]
            out = None
            if len(batch) > 1:
                out = gtx_translate_batch(texts, sl, tl, a.timeout, a.retries)
            if out is None:  # per-key (single item, or batch misaligned/failed)
                out = []
                for _, t, _ in batch:
                    try:
                        out.append(gtx_translate(t, sl, tl, a.timeout, a.retries))
                    except Exception:                # noqa: BLE001
                        out.append(None)
            return batch, out

        with ThreadPoolExecutor(max_workers=a.workers) as ex:
            for batch, out in ex.map(run_batch, batches):
                for (k, text, sl), tr in zip(batch, out):
                    if tr is None:
                        n_err += 1
                        results[k] = text  # fallback to source
                    else:
                        results[k] = tr
                        cache[f"{tl}|{sl}|{text}"] = tr
        total_calls += len(batches)

        ordered = [(k, results[k]) for k in key_order if k in results]
        (dump_json if fmt == "json" else dump_properties)(out_path, ordered)
        if not a.no_cache:
            json.dump(cache, open(cache_path, "w", encoding="utf-8"), ensure_ascii=False)
        print(f"[{ci}/{len(targets)}] {code:<9} +{len(todo)} keys"
              f"{f' ({n_err} fallbacks)' if n_err else ''}")

    print(f"done. ~{total_calls} translation calls.")


if __name__ == "__main__":
    main()
